language: node_js
node_js:
  - "12"
dist: trusty
sudo: false
cache: yarn
install:
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - xvfb